"use client";

import { useEffect, useState, useCallback, useMemo } from "react";
import { useRouter } from "next/navigation";
import type { CaseStudyCandidate } from "@/lib/db/schema";

// ─── Types ──────────────────────────────────────────────────────────────────

type ScanResult = {
  scanned: number;
  newCandidates: number;
  autoGenerated: number;
  errors: string[];
  completedAt: string;
};

const STATUSES = [
  "all",
  "suggested",
  "generating",
  "generated",
  "reviewed",
  "published",
  "excluded",
  "ignored",
] as const;

type StatusFilter = (typeof STATUSES)[number];

const STATUS_LABELS: Record<StatusFilter, string> = {
  all: "All",
  suggested: "Suggested",
  generating: "Generating",
  generated: "Generated",
  reviewed: "Reviewed",
  published: "Published",
  excluded: "Excluded",
  ignored: "Ignored",
};

// ─── Helpers ────────────────────────────────────────────────────────────────

function getStatusBadgeClasses(status: string): string {
  switch (status) {
    case "suggested":
      return "bg-blue-100 text-blue-700";
    case "generating":
      return "bg-yellow-100 text-yellow-700";
    case "generated":
      return "bg-emerald-100 text-emerald-700";
    case "reviewed":
      return "bg-purple-100 text-purple-700";
    case "published":
      return "bg-green-100 text-green-800";
    case "excluded":
      return "bg-red-100 text-red-700";
    case "ignored":
      return "bg-neutral-200 text-neutral-600";
    default:
      return "bg-neutral-200 text-neutral-600";
  }
}

function formatDate(date: string | null | undefined): string {
  if (!date) return "--";
  const d = new Date(date);
  if (isNaN(d.getTime())) return "--";
  return d.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatScore(score: number): string {
  return `${score}/100`;
}

function getScoreColor(score: number): string {
  if (score >= 70) return "text-green-700";
  if (score >= 40) return "text-yellow-700";
  return "text-red-700";
}

// ─── Page Component ─────────────────────────────────────────────────────────

export default function CaseStudiesPage() {
  const router = useRouter();
  const [candidates, setCandidates] = useState<CaseStudyCandidate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Scan state
  const [scanning, setScanning] = useState(false);
  const [scanResult, setScanResult] = useState<ScanResult | null>(null);

  // Filters
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [clientSearch, setClientSearch] = useState("");
  const [minScore, setMinScore] = useState("");

  // Action loading state (track which candidate IDs are being updated)
  const [actionLoading, setActionLoading] = useState<Set<string>>(new Set());

  // ─── Fetch candidates ───────────────────────────────────────────────────

  const fetchCandidates = useCallback(async () => {
    setError(null);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== "all") params.set("status", statusFilter);
      if (clientSearch.trim()) params.set("client", clientSearch.trim());
      if (minScore.trim()) params.set("minScore", minScore.trim());

      const res = await fetch(
        `/api/admin/case-studies/candidates?${params.toString()}`
      );
      if (!res.ok) {
        throw new Error(`Failed to fetch candidates (${res.status})`);
      }
      const data: CaseStudyCandidate[] = await res.json();
      setCandidates(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, [statusFilter, clientSearch, minScore]);

  useEffect(() => {
    fetchCandidates();
  }, [fetchCandidates]);

  // Auto-poll when any candidate is "generating"
  useEffect(() => {
    const hasGenerating = candidates.some((c) => c.status === "generating");
    if (!hasGenerating) return;
    const interval = setInterval(fetchCandidates, 5000);
    return () => clearInterval(interval);
  }, [candidates, fetchCandidates]);

  // ─── Scan action ────────────────────────────────────────────────────────

  const runScan = useCallback(async () => {
    setScanning(true);
    setScanResult(null);
    try {
      const res = await fetch("/api/admin/case-studies/scan", {
        method: "POST",
      });
      if (!res.ok) {
        throw new Error(`Scan failed (${res.status})`);
      }
      const result: ScanResult = await res.json();
      setScanResult(result);
      // Refresh candidate list after scan
      await fetchCandidates();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Scan failed");
    } finally {
      setScanning(false);
    }
  }, [fetchCandidates]);

  // ─── Status change action ──────────────────────────────────────────────

  const updateStatus = useCallback(
    async (
      id: string,
      status: string,
      extra?: { excludedReason?: string }
    ) => {
      setActionLoading((prev) => new Set(prev).add(id));
      try {
        const res = await fetch(`/api/admin/case-studies/candidates/${id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ status, ...extra }),
        });
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(
            errData.error || `Failed to update status (${res.status})`
          );
        }
        // Refresh list
        await fetchCandidates();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Update failed");
      } finally {
        setActionLoading((prev) => {
          const next = new Set(prev);
          next.delete(id);
          return next;
        });
      }
    },
    [fetchCandidates]
  );

  // ─── Generate action (real LLM) ──────────────────────────────────────

  const generateCaseStudy = useCallback(
    async (id: string, force: boolean = false) => {
      setActionLoading((prev) => new Set(prev).add(id));
      try {
        const res = await fetch(
          `/api/admin/case-studies/candidates/${id}/generate`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ force }),
          }
        );
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(
            errData.error || `Generation failed (${res.status})`
          );
        }
        await fetchCandidates();
      } catch (err) {
        setError(err instanceof Error ? err.message : "Generation failed");
      } finally {
        setActionLoading((prev) => {
          const next = new Set(prev);
          next.delete(id);
          return next;
        });
      }
    },
    [fetchCandidates]
  );

  // ─── Derived data ─────────────────────────────────────────────────────

  const statusCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const c of candidates) {
      counts[c.status] = (counts[c.status] || 0) + 1;
    }
    return counts;
  }, [candidates]);

  // ─── Render ───────────────────────────────────────────────────────────

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-brand-black">
            Case Study Pipeline
          </h1>
          <p className="text-neutral-500 text-sm mt-1">
            Scan projects, score their case study potential, and generate content
          </p>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <button
            onClick={runScan}
            disabled={scanning}
            className="inline-flex items-center gap-1.5 px-4 py-2 bg-brand-black text-white text-sm font-semibold rounded-lg hover:bg-neutral-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {scanning && (
              <svg
                className="w-4 h-4 animate-spin"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                aria-hidden="true"
              >
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
            )}
            {scanning ? "Scanning..." : "Run Scan"}
          </button>
        </div>
      </div>

      {/* Scan result toast */}
      {scanResult && (
        <div className="flex items-center gap-3 px-4 py-3 bg-emerald-50 border border-emerald-200 rounded-lg text-sm text-emerald-800">
          <svg
            className="w-4 h-4 shrink-0"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
            <polyline points="22 4 12 14.01 9 11.01" />
          </svg>
          <span>
            Scan complete &mdash; {scanResult.scanned} projects scanned,{" "}
            {scanResult.newCandidates} new candidates found.
          </span>
          <button
            onClick={() => setScanResult(null)}
            className="ml-auto text-emerald-600 hover:text-emerald-800"
            aria-label="Dismiss"
          >
            <svg
              className="w-4 h-4"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      )}

      {/* Error banner */}
      {error && (
        <div className="flex items-center gap-3 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-800">
          <span>Error: {error}</span>
          <button
            onClick={() => setError(null)}
            className="ml-auto text-red-600 hover:text-red-800"
            aria-label="Dismiss error"
          >
            <svg
              className="w-4 h-4"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      )}

      {/* Status summary badges */}
      {!loading && candidates.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {(
            [
              "suggested",
              "generated",
              "reviewed",
              "published",
              "excluded",
            ] as const
          ).map((s) => (
            <span
              key={s}
              className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium ${getStatusBadgeClasses(s)}`}
            >
              {STATUS_LABELS[s]}
              <span className="font-bold">{statusCounts[s] || 0}</span>
            </span>
          ))}
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3">
        {/* Status filter */}
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value as StatusFilter)}
          className="px-3 py-2 border border-neutral-300 rounded-lg text-sm bg-white text-brand-black focus:outline-none focus:ring-2 focus:ring-brand-black/20"
        >
          {STATUSES.map((s) => (
            <option key={s} value={s}>
              {STATUS_LABELS[s]}
            </option>
          ))}
        </select>

        {/* Client search */}
        <div className="relative flex-1 max-w-xs">
          <svg
            className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-400"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            type="text"
            value={clientSearch}
            onChange={(e) => setClientSearch(e.target.value)}
            placeholder="Search by client name..."
            className="w-full pl-9 pr-3 py-2 border border-neutral-300 rounded-lg text-sm bg-white text-brand-black placeholder:text-neutral-400 focus:outline-none focus:ring-2 focus:ring-brand-black/20"
          />
        </div>

        {/* Min score */}
        <input
          type="number"
          value={minScore}
          onChange={(e) => setMinScore(e.target.value)}
          placeholder="Min score"
          min="0"
          max="100"
          className="w-28 px-3 py-2 border border-neutral-300 rounded-lg text-sm bg-white text-brand-black placeholder:text-neutral-400 focus:outline-none focus:ring-2 focus:ring-brand-black/20"
        />
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-neutral-300 overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center py-16">
            <svg
              className="w-6 h-6 animate-spin text-neutral-400"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              aria-hidden="true"
            >
              <path d="M21 12a9 9 0 1 1-6.219-8.56" />
            </svg>
            <span className="ml-3 text-sm text-neutral-500">
              Loading candidates...
            </span>
          </div>
        ) : candidates.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <svg
              className="w-10 h-10 text-neutral-300 mb-3"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <rect x="2" y="7" width="20" height="14" rx="2" />
              <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
            </svg>
            <p className="text-sm text-neutral-500 mb-4">
              No candidates found. Run a scan to populate the pipeline.
            </p>
            <button
              onClick={runScan}
              disabled={scanning}
              className="inline-flex items-center gap-1.5 px-4 py-2 bg-brand-black text-white text-sm font-semibold rounded-lg hover:bg-neutral-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {scanning ? "Scanning..." : "Run Scan"}
            </button>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <caption className="sr-only">
                Case study candidates pipeline
              </caption>
              <thead>
                <tr className="border-b border-neutral-200 text-left">
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Client
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Project
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Type
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Score
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Status
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Scanned
                  </th>
                  <th className="px-5 py-3 text-xs font-semibold text-neutral-500 uppercase tracking-wider whitespace-nowrap">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                {candidates.map((c, i) => (
                  <tr
                    key={c.id}
                    onClick={() => router.push(`/admin/agents/case-studies/${c.id}`)}
                    className={`border-b border-neutral-100 hover:bg-neutral-50 transition-colors cursor-pointer ${
                      i % 2 === 0 ? "bg-white" : "bg-neutral-50/50"
                    }`}
                  >
                    {/* Client */}
                    <td className="px-5 py-3.5 text-sm font-medium text-brand-black whitespace-nowrap">
                      {c.clientName}
                    </td>

                    {/* Project */}
                    <td className="px-5 py-3.5 text-sm text-brand-black max-w-[220px] truncate">
                      {c.projectName || "--"}
                    </td>

                    {/* Type */}
                    <td className="px-5 py-3.5 text-sm text-neutral-600 whitespace-nowrap">
                      {c.projectType || "--"}
                    </td>

                    {/* Score */}
                    <td className="px-5 py-3.5 whitespace-nowrap">
                      <span
                        className={`text-sm font-semibold ${getScoreColor(c.scoreTotal)}`}
                      >
                        {formatScore(c.scoreTotal)}
                      </span>
                      {/* Score bar */}
                      <div className="mt-1 w-20 h-1.5 bg-neutral-200 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${
                            c.scoreTotal >= 70
                              ? "bg-green-500"
                              : c.scoreTotal >= 40
                                ? "bg-yellow-500"
                                : "bg-red-400"
                          }`}
                          style={{ width: `${c.scoreTotal}%` }}
                        />
                      </div>
                    </td>

                    {/* Status */}
                    <td className="px-5 py-3.5">
                      <span
                        className={`inline-flex px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusBadgeClasses(c.status)}`}
                      >
                        {c.status.charAt(0).toUpperCase() + c.status.slice(1)}
                      </span>
                    </td>

                    {/* Scanned date */}
                    <td className="px-5 py-3.5 text-sm text-neutral-600 whitespace-nowrap">
                      {formatDate(
                        c.lastScannedAt
                          ? String(c.lastScannedAt)
                          : null
                      )}
                    </td>

                    {/* Actions */}
                    <td className="px-5 py-3.5">
                      <div className="flex items-center gap-2">
                        {/* Generate — only for suggested/ignored */}
                        {(c.status === "suggested" ||
                          c.status === "ignored") && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              generateCaseStudy(c.id, c.scoreTotal < 70);
                            }}
                            disabled={actionLoading.has(c.id)}
                            className="inline-flex items-center gap-1 px-2.5 py-1 bg-brand-black text-white text-xs font-medium rounded-md hover:bg-neutral-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                            title="Generate case study with AI"
                          >
                            {actionLoading.has(c.id) ? (
                              <svg
                                className="w-3 h-3 animate-spin"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                              >
                                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                              </svg>
                            ) : (
                              <svg
                                className="w-3 h-3"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
                              </svg>
                            )}
                            Generate
                          </button>
                        )}

                        {/* Exclude — available for non-excluded statuses */}
                        {c.status !== "excluded" &&
                          c.status !== "published" && (
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                updateStatus(c.id, "excluded", {
                                  excludedReason: "Not representative",
                                });
                              }}
                              disabled={actionLoading.has(c.id)}
                              className="inline-flex items-center gap-1 px-2.5 py-1 border border-neutral-300 text-neutral-600 text-xs font-medium rounded-md hover:bg-neutral-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                              title="Exclude from pipeline"
                            >
                              Exclude
                            </button>
                          )}

                        {/* Restore — for excluded candidates */}
                        {c.status === "excluded" && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              updateStatus(c.id, "suggested");
                            }}
                            disabled={actionLoading.has(c.id)}
                            className="inline-flex items-center gap-1 px-2.5 py-1 border border-neutral-300 text-neutral-600 text-xs font-medium rounded-md hover:bg-neutral-100 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                            title="Restore to pipeline"
                          >
                            Restore
                          </button>
                        )}

                        {/* Mark as Reviewed — for generated */}
                        {c.status === "generated" && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              updateStatus(c.id, "reviewed");
                            }}
                            disabled={actionLoading.has(c.id)}
                            className="inline-flex items-center gap-1 px-2.5 py-1 border border-emerald-300 text-emerald-700 text-xs font-medium rounded-md hover:bg-emerald-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                            title="Mark as reviewed"
                          >
                            Reviewed
                          </button>
                        )}

                        {/* Publish — for reviewed */}
                        {c.status === "reviewed" && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              router.push(`/admin/agents/case-studies/${c.id}`);
                            }}
                            disabled={actionLoading.has(c.id)}
                            className="inline-flex items-center gap-1 px-2.5 py-1 bg-green-700 text-white text-xs font-medium rounded-md hover:bg-green-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                            title="View and publish case study"
                          >
                            View & Publish
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Total count */}
      {!loading && candidates.length > 0 && (
        <p className="text-xs text-neutral-400">
          Showing {candidates.length} candidate
          {candidates.length !== 1 ? "s" : ""}
        </p>
      )}
    </div>
  );
}
