-- Action 5: Arya learning journal + rules
-- Source: docs/pm/arya-specs-v2.md (Action 5 data model)

CREATE TABLE IF NOT EXISTS arya_learnings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date TIMESTAMP DEFAULT NOW() NOT NULL,
  pm_name VARCHAR(100) NOT NULL,
  item_type VARCHAR(50) NOT NULL,
  -- 'email_draft', 'brief', 'quote', 'pitch', 'followup', 'ack_receipt'
  item_id VARCHAR(255),
  -- ID of the inbox_item or document corrected
  arya_original TEXT NOT NULL,
  pm_edited TEXT NOT NULL,
  diff_summary TEXT,
  -- generated by Haiku
  category VARCHAR(50) NOT NULL,
  -- 'ton', 'contenu', 'structure', 'pricing', 'missing_info'
  category_confirmed BOOLEAN DEFAULT false,
  promoted BOOLEAN DEFAULT false,
  promoted_rule_id UUID,
  -- FK to arya_rules if promoted (nullable)
  project_id VARCHAR(255),
  client_domain VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_arya_learnings_category ON arya_learnings(category);
CREATE INDEX IF NOT EXISTS idx_arya_learnings_item_type ON arya_learnings(item_type);
CREATE INDEX IF NOT EXISTS idx_arya_learnings_promoted ON arya_learnings(promoted);

-- Rules promoted from learnings
CREATE TABLE IF NOT EXISTS arya_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_text TEXT NOT NULL,
  category VARCHAR(50) NOT NULL,
  -- 'ton', 'contenu', 'structure', 'pricing', 'missing_info'
  source_learning_ids JSONB DEFAULT '[]',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  deactivated_at TIMESTAMP,
  deactivation_reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_arya_rules_active ON arya_rules(active);
CREATE INDEX IF NOT EXISTS idx_arya_rules_category ON arya_rules(category);

-- Add FK after arya_rules is created
ALTER TABLE arya_learnings
  ADD CONSTRAINT fk_arya_learnings_rule
  FOREIGN KEY (promoted_rule_id) REFERENCES arya_rules(id) ON DELETE SET NULL;
