"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { CONTRACT_TYPE_LABELS, type ContractType } from "@/lib/validations/legal";

// ─── Types ──────────────────────────────────────────────────────────────────

type HistoryEntry = {
  id: string;
  clientId: string;
  clientName: string;
  inputPayload: {
    contractType: ContractType;
    projectDescription: string;
    amount: number;
    currency: string;
    language: string;
  } | null;
  outputContent: string | null;
  status: string;
  createdAt: string;
};

// ─── Page Component ─────────────────────────────────────────────────────────

export default function LegalHistoryPage() {
  const [entries, setEntries] = useState<HistoryEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const fetchHistory = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/agents/legal/history");
      if (!res.ok) {
        throw new Error("Failed to fetch history");
      }
      const data = await res.json();
      setEntries(data);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to load history"
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchHistory();
  }, [fetchHistory]);

  async function handleCopy(text: string, id: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    } catch {
      // silent fail
    }
  }

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString("en-GB", {
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  }

  // ── Render ──────────────────────────────────────────────────────────────

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-brand-black">
            Contract History
          </h1>
          <p className="text-neutral-500 text-sm mt-1">
            All contracts generated by Legal IA
          </p>
        </div>
        <Link
          href="/admin/agents/legal"
          className="px-4 py-2 bg-brand-black text-white text-sm font-semibold rounded-lg hover:bg-neutral-800 transition-colors"
        >
          New Contract
        </Link>
      </div>

      {/* Loading */}
      {loading && (
        <div className="bg-white rounded-xl border border-neutral-300 p-8 text-center text-sm text-neutral-400">
          Loading history...
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-4 py-3">
          {error}
        </div>
      )}

      {/* Empty state */}
      {!loading && !error && entries.length === 0 && (
        <div className="bg-white rounded-xl border border-neutral-300 p-8 text-center">
          <p className="text-sm text-neutral-500">
            No contracts generated yet.
          </p>
          <Link
            href="/admin/agents/legal"
            className="text-sm font-medium text-brand-cerulean hover:underline mt-2 inline-block"
          >
            Generate your first contract
          </Link>
        </div>
      )}

      {/* History entries */}
      {entries.length > 0 && (
        <div className="space-y-3">
          {entries.map((entry) => {
            const payload = entry.inputPayload;
            const isExpanded = expandedId === entry.id;

            return (
              <div
                key={entry.id}
                className="bg-white rounded-xl border border-neutral-300 overflow-hidden"
              >
                {/* Summary row */}
                <button
                  onClick={() =>
                    setExpandedId(isExpanded ? null : entry.id)
                  }
                  className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-neutral-50 transition-colors"
                >
                  <div className="flex items-center gap-3 min-w-0">
                    <span className="text-xs font-medium bg-neutral-200 text-neutral-700 px-2 py-0.5 rounded shrink-0">
                      {payload?.contractType || "Contract"}
                    </span>
                    <span className="text-sm font-medium text-brand-black truncate">
                      {entry.clientName}
                    </span>
                    {payload && (
                      <span className="text-xs text-neutral-500 shrink-0">
                        {payload.amount.toLocaleString()} {payload.currency}
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    <span
                      className={`text-xs px-1.5 py-0.5 rounded ${
                        entry.status === "done"
                          ? "bg-green-100 text-green-700"
                          : entry.status === "error"
                            ? "bg-red-100 text-red-700"
                            : "bg-neutral-100 text-neutral-600"
                      }`}
                    >
                      {entry.status}
                    </span>
                    <span className="text-xs text-neutral-400">
                      {formatDate(entry.createdAt)}
                    </span>
                    <span className="text-neutral-400 text-sm">
                      {isExpanded ? "\u25B2" : "\u25BC"}
                    </span>
                  </div>
                </button>

                {/* Expanded content */}
                {isExpanded && entry.outputContent && (
                  <div className="border-t border-neutral-200 px-5 py-4 space-y-3">
                    {/* Meta info */}
                    {payload && (
                      <div className="text-xs text-neutral-500 space-y-1">
                        <p>
                          Type:{" "}
                          {CONTRACT_TYPE_LABELS[payload.contractType] ||
                            payload.contractType}
                        </p>
                        <p>Description: {payload.projectDescription}</p>
                        <p>
                          Language:{" "}
                          {payload.language === "fr" ? "French" : "English"}
                        </p>
                      </div>
                    )}

                    {/* Legal warning */}
                    <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-xs text-amber-800">
                      This contract has not been reviewed by legal counsel.
                    </div>

                    {/* Contract text */}
                    <div className="border border-neutral-200 rounded-lg p-4 max-h-[400px] overflow-y-auto">
                      <div className="prose prose-sm prose-neutral max-w-none whitespace-pre-wrap text-xs leading-relaxed">
                        {entry.outputContent}
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex justify-end gap-2">
                      <button
                        onClick={() =>
                          handleCopy(entry.outputContent!, entry.id)
                        }
                        className="px-3 py-1.5 text-xs font-medium border border-neutral-300 rounded-lg hover:bg-neutral-100 transition-colors text-brand-black"
                      >
                        {copiedId === entry.id ? "Copied!" : "Copy"}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
