import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { caseStudyCandidates } from "@/lib/db/schema";
import { eq } from "drizzle-orm";

/**
 * POST /api/admin/case-studies/scan
 *
 * V1 Foundation: returns mock scan results.
 * Real ClickUp + SharePoint integration will be added in a later phase.
 */
export async function POST() {
  try {
    // Mock scan data — simulates projects found in ClickUp
    const mockProjects = [
      {
        clickupTaskId: `mock-${Date.now()}-1`,
        clientName: "TikTok",
        projectName: "Brand Campaign Q1 2026",
        projectType: "Campaign",
        projectAmount: "22000",
        completedAt: new Date("2026-02-15"),
        sharePointAssetCount: 14,
        scoreTotal: 87,
        scoreBreakdown: {
          clientName: 25,
          amount: 20,
          assets: 20,
          projectType: 15,
          recency: 7,
          diversity: 0,
        },
        status: "suggested" as const,
      },
      {
        clickupTaskId: `mock-${Date.now()}-2`,
        clientName: "GEODIS",
        projectName: "Corporate Rebranding",
        projectType: "Rebranding",
        projectAmount: "8500",
        completedAt: new Date("2026-01-20"),
        sharePointAssetCount: 6,
        scoreTotal: 63,
        scoreBreakdown: {
          clientName: 15,
          amount: 12,
          assets: 12,
          projectType: 15,
          recency: 6,
          diversity: 3,
        },
        status: "suggested" as const,
      },
      {
        clickupTaskId: `mock-${Date.now()}-3`,
        clientName: "Sony",
        projectName: "Product Launch Video",
        projectType: "Video Production",
        projectAmount: "15000",
        completedAt: new Date("2025-11-10"),
        sharePointAssetCount: 22,
        scoreTotal: 78,
        scoreBreakdown: {
          clientName: 25,
          amount: 20,
          assets: 20,
          projectType: 15,
          recency: 6,
          diversity: -8,
        },
        status: "suggested" as const,
      },
    ];

    let newCandidates = 0;

    for (const project of mockProjects) {
      // Check if candidate already exists (by clickup task ID)
      const existing = await db
        .select({ id: caseStudyCandidates.id })
        .from(caseStudyCandidates)
        .where(
          eq(caseStudyCandidates.clickupTaskId, project.clickupTaskId)
        )
        .limit(1);

      if (existing.length === 0) {
        await db.insert(caseStudyCandidates).values({
          clickupTaskId: project.clickupTaskId,
          clientName: project.clientName,
          projectName: project.projectName,
          projectType: project.projectType,
          projectAmount: project.projectAmount,
          completedAt: project.completedAt,
          sharePointAssetCount: project.sharePointAssetCount,
          scoreTotal: project.scoreTotal,
          scoreBreakdown: project.scoreBreakdown,
          status: project.status,
          lastScannedAt: new Date(),
        });
        newCandidates++;
      } else {
        // Update scan timestamp
        await db
          .update(caseStudyCandidates)
          .set({ lastScannedAt: new Date(), updatedAt: new Date() })
          .where(eq(caseStudyCandidates.id, existing[0].id));
      }
    }

    return NextResponse.json({
      scanned: mockProjects.length,
      newCandidates,
      autoGenerated: 0,
      errors: [],
      completedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("Error running case study scan:", error);
    return NextResponse.json(
      { error: "Scan failed" },
      { status: 500 }
    );
  }
}
