import type { Metadata } from "next";
import Link from "next/link";
import { Section } from "@/components/layout/section";
import { BreadcrumbSchema } from "@/components/seo/breadcrumb-schema";
import { BREADCRUMBS } from "@/lib/breadcrumb-jsonld";
import { db } from "@/lib/db";
import { caseStudyOutputs } from "@/lib/db/schema";
import { eq, isNotNull, and, desc } from "drizzle-orm";
import { type CaseStudyOutput } from "@/lib/case-studies/schemas";
import { Button } from "@/components/ui/button";

// ISR — revalidates every hour to pick up newly published case studies.
export const revalidate = 3600;

export const metadata: Metadata = {
  title: "Case Studies — Real Results for Global Brands | Sarani",
  description:
    "See how Sarani delivers enterprise creative at scale. Real briefs, real deadlines, real results for TikTok, Sony, Adidas, LEGO, IKEA, GEODIS, and more.",
  openGraph: {
    title: "Case Studies — Real Results for Global Brands | Sarani",
    description:
      "Real briefs. Real deadlines. Real results. Enterprise creative at scale.",
    url: "/case-studies",
  },
  alternates: {
    canonical: "https://sarani.studio/case-studies",
  },
};

/* ---------- Data fetching ---------- */

async function fetchAllPublishedCaseStudies(): Promise<CaseStudyOutput[]> {
  try {
    const rows = await db
      .select({
        content: caseStudyOutputs.content,
        publishedAt: caseStudyOutputs.publishedAt,
      })
      .from(caseStudyOutputs)
      .where(
        and(
          eq(caseStudyOutputs.outputType, "case_study"),
          isNotNull(caseStudyOutputs.publishedAt)
        )
      )
      .orderBy(desc(caseStudyOutputs.publishedAt));

    return rows.map((row) => row.content as unknown as CaseStudyOutput);
  } catch {
    // DB unavailable — return empty list gracefully
    return [];
  }
}

/* ---------- Page ---------- */

export default async function CaseStudiesIndexPage() {
  const caseStudies = await fetchAllPublishedCaseStudies();

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "Case Studies — Sarani",
    description:
      "Published case studies showcasing Sarani's enterprise creative work.",
    url: "https://sarani.studio/case-studies",
    publisher: {
      "@type": "Organization",
      name: "Sarani",
      url: "https://sarani.studio",
    },
  };

  return (
    <div className="bg-brand-black pt-[var(--header-height)]">
      <BreadcrumbSchema items={BREADCRUMBS.caseStudies} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* ── Hero ── */}
      <Section ariaLabel="Case studies overview">
        <p className="mb-4 text-xs font-medium uppercase tracking-[0.2em] text-brand-flame">
          Case Studies
        </p>
        <h1 className="mb-6 text-4xl font-bold leading-tight tracking-tight text-white sm:text-5xl lg:text-6xl">
          Real results. Proven at scale.
        </h1>
        <p className="mb-4 max-w-2xl text-lg leading-relaxed text-neutral-400">
          From pipeline to publication — case studies generated by our AI
          pipeline and reviewed by the Sarani team.
        </p>
      </Section>

      {/* ── Grid ── */}
      <Section ariaLabel="Published case studies">
        {caseStudies.length === 0 ? (
          <div className="py-16 text-center">
            <p className="text-lg text-neutral-500">
              No case studies published yet. Check back soon.
            </p>
            <div className="mt-6">
              <Button variant="primary" href="/work">
                View our work
              </Button>
            </div>
          </div>
        ) : (
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {caseStudies.map((cs) => (
              <Link
                key={cs.slug}
                href={`/case-studies/${cs.slug}`}
                className="group flex flex-col rounded-2xl border border-white/10 bg-white/5 p-8 transition-all duration-200 hover:border-brand-lemon/40 hover:bg-white/10"
              >
                {/* Top row: metric badge + category */}
                <div className="mb-4 flex flex-wrap items-center gap-2">
                  <span className="inline-block rounded-full bg-brand-flame/20 px-3 py-1 text-xs font-bold text-brand-flame">
                    {cs.keyMetric}
                  </span>
                  <span className="inline-block rounded-full border border-white/10 px-3 py-1 text-xs font-medium text-neutral-500">
                    {cs.category}
                  </span>
                </div>

                <p className="mb-1 text-sm font-medium uppercase tracking-wider text-brand-flame">
                  {cs.client}
                </p>
                <p className="mb-4 text-lg font-bold leading-snug text-white">
                  {cs.headline}
                </p>

                {/* Stat highlight — first stat */}
                {cs.stats && cs.stats.length > 0 && (
                  <div className="mt-auto flex items-baseline gap-2 border-t border-white/10 pt-4">
                    <span className="text-2xl font-bold text-brand-lemon">
                      {cs.stats[0].value}
                    </span>
                    <span className="text-sm text-neutral-500">
                      {cs.stats[0].label}
                    </span>
                  </div>
                )}
              </Link>
            ))}
          </div>
        )}
      </Section>

      {/* ── CTA ── */}
      <Section ariaLabel="Start your project">
        <div className="text-center">
          <h2 className="mb-4 text-3xl font-bold text-white sm:text-4xl">
            Your brief could be next.
          </h2>
          <p className="mx-auto mb-8 max-w-xl text-neutral-500">
            First project satisfaction or no invoice.
          </p>
          <Button variant="primary" href="/contact">
            Start a project
          </Button>
        </div>
      </Section>
    </div>
  );
}
